### ISSUE TITLE
Resource Owner Password Flow not supported (?)

### ISSUE THREAD

**Issue by ctron** [kilork/openid#15]
To me it looks like as if the "Resource Owner Password Flow" isn't supported.

**Comment by ctron** [comment]
Here is the spec: https://tools.ietf.org/html/rfc6749#section-4.3

If you like, I could prepare a PR for implementing this.

**Comment by kilork** [comment]
I really do not have anything against it. I both do not use all flows and have not wrote original implementation. But any improvement including overall design would be really helpful.
