### ISSUE TITLE
`decode_token` may panic

### ISSUE THREAD

**Issue by ctron** [kilork/openid#23]
To me it looks like `decode_token` may panic, due to the use of `unimplemented!`.

So if a user provided token contains a algorithm which is not supported, that could let the function panic.

I think handling the situation gracefully, with a proper error return, would be better.

**Comment by kilork** [comment]
I think it is an issue, which I introduced during library version upgrade, we should introduce just normal error to not break everything in panic.

**Comment by ctron** [comment]
Awesome! Thank you for the quick fix and release!

**Comment by kilork** [comment]
You are welcome :)
