### ISSUE TITLE
Cannot save openId::Token to async_session::Session.

### ISSUE THREAD

**Issue by kokihonda** [kilork/openid#27]
I tried to save the openId::Token in async_session::Session, but I couldn't because the insert function of async_session::Session requires the implementation of Serialize, but openId::Token doesn't implement it.

Is it possible to implement Serialize in openId::Token?

https://docs.rs/async-session/3.0.0/async_session/struct.Session.html#method.insert
https://docs.rs/openid/0.9.3/openid/struct.Token.html

**Comment by kilork** [comment]
Hi, you can use [bearer](https://docs.rs/openid/0.9.3/openid/struct.Token.html#structfield.bearer) field of openid::Token structure.

https://docs.rs/openid/0.9.3/openid/struct.Token.html#structfield.bearer

**Comment by kokihonda** [comment]
Thank you!

I didn't understand that I don't need to store  ID token in the session.

**Comment by kilork** [comment]
Yeap, my favourite development principle is YAGNI :)
