### ISSUE TITLE
Bearer’s expires field gets scrambled after serialize → deserialize round-trip

### ISSUE THREAD

**Issue by silmeth** [kilork/openid#47]
When `Bearer` is [deserialized](https://github.com/kilork/openid/blob/d0fb36bcae1ef93f64a5f7c61e1fffdc803ae578/src/bearer.rs#L23-L53) it expects the `expires_in` field in seconds-from-now, and [adds a `Utc::now()` to it](https://github.com/kilork/openid/blob/d0fb36bcae1ef93f64a5f7c61e1fffdc803ae578/src/bearer.rs#L48) in order to obtain a fixed non-relative UTC instant. That makes sense.

But then when [it is serialized](https://github.com/kilork/openid/blob/d0fb36bcae1ef93f64a5f7c61e1fffdc803ae578/src/bearer.rs#L55-L63) it [directly serializes `expires.timestamp()`](https://github.com/kilork/openid/blob/d0fb36bcae1ef93f64a5f7c61e1fffdc803ae578/src/bearer.rs#L60) (Unix timestamp in secodns) as the `expires_in` field – which is not consistent.

This means that if you save the serialized `bearer` value eg. for session keeping then each time you deserialize it you add a Unix timestamp `Utc::now()` worth amount of seconds to the `expires` field, making it unusable.

There should be either type for the serialize-deserialize round-trip (a `SerializableBearer` type that just has `expires` field?) or some other way to restore it from serialization.

**Comment by Lesny** [comment]
I created PR with example fix
https://github.com/kilork/openid/pull/48/files

**Comment by kilork** [comment]
Should we try to do anything about this field actually? I am thinking about removing original field and providing the structure to use as wrapper instead.

We could have 

```rust
...
struct Bearer {
  expires_in: Option<u64>,
  ...
}

...
struct BearerReceived {
  bearer: Bearer,
  expires_at: Option<DateTime<Utc>>,
}
```

More simple design should be better and one who consumes library can decide, how to store it better, or use our provided wrapper. What do you think?

Also we do not really use this field in library, only part responsible for token refresh. Which is most probably not used by anyone directly, as `id_token` has its own `exp` field.

**Comment by kyrias** [comment]
Personally I only care about it in that I need a reliable way to do token refreshing, but since my use-case involves ID tokens I don't necessarily need it, as you pointed out, so as long as there's a reliable way to check whether or not the token has expired then I don't really care how it's actually stored.  Theoretically there might be people using OIDC without actually receiving an ID token though, but I'm not sure why anyone would.

Though `BearerReceived` feels a bit misleading when the only thing it contains in addition to the `Bearer` struct is derived data which _wasn't_ received.

**Comment by kilork** [comment]
@kyrias this is the most difficult part always. To name the things. My intention was to name it to show a state "Bearer After It Was Received", cause lifetime is counted starting from response created and as it is finally received - we can build expiration date. But of course, if it is misleading would be nice to have better suggestion.
